---

- name: Create the filesystem if necessary
  filesystem:
    dev: "{{ atl_nfs_server_device }}"
    fstype: "{{ atl_nfs_fs_type }}"
    opts:
      - "-L {{ atl_nfs_fs_label }}"

- name: Create mountpoint
  file:
    path: "{{ atl_shared_mountpoint }}"
    state: directory
    mode: 0750
    owner: "{{ atl_product_user }}"
    group: "{{ atl_product_user }}"

- name: Setup fstab and mount the filesystem
  mount:
    path: "{{ atl_shared_mountpoint }}"
    src: "{{ atl_nfs_server_device }}:/"
    state: mounted
