---

#
# STRUCTURE
#
# mode:
#   filesystem:
#     retained: []
#   database:
#     retained:
#       tables: []
#       queries:
#         table1:
#           - query1
#           - query2
#         table2:
#           - query3
#           - query4
#     substitutions:
#       tables:
#         - table1
#         - table2
#       strings:
#         string1: subst1
#         string2: subst2

#
# What we want for a CLONE PROVISION
#
clone:
  filesystem:
    retained:
      - '*/cluster.properties'
      - '*/dbconfig.xml'
  database:
    retained:
      tables: []
      queries:
        propertystring:
          - id = (select ID from propertyentry where property_key = 'jira.title')
    substitutions:
      tables: []
      strings: []
          
#        
# What we (probably) want for a CLONE REFRESH
#
refresh:
  filesystem:
    retained:
      - '*/cluster.properties'
      - '*/dbconfig.xml'
      - '*/keys/*'
      - '*/secrets-config.yaml'
      - '*/secured/*'
      # - '*/filestore-config.yaml' # For s3 attachments 
  database:
    retained:
      tables:
        - 'cwd_%'
        - AO_ED669C_IDP_CONFIG
        - mailserver
      queries:
        propertystring:
          - id = (select ID from propertyentry where property_key = 'jira.title')
    substitutions:
      tables: []
      strings: []
