---

# Note: We don't the cache binary in the shared drive to the complexity
# around download race-conditions if multiple nodes are starting at
# the same time. When downloading from product-downloads.atlassian.com
# (which is a CDN) takes seconds anyway.
- name: Fetch product installer
  get_url:
    url: "{{ atl_product_download_url }}"
    dest: "{{ atl_product_download }}"
    mode: 0755
    force: false

- name: Create installer varfile
  template:
    src: "{{ atl_product_family }}.varfile.j2"
    dest: "{{ atl_product_varfile }}"

- name: Run the installer
  command: /bin/sh "{{ atl_product_download }}" -q -varfile "{{ atl_product_varfile }}"
  args:
    creates: "{{ atl_product_installation_versioned }}/.install4j/"

- name: Symlink the installed version to current
  file:
    src: "{{ atl_product_installation_versioned }}"
    dest: "{{ atl_product_installation_current }}"
    state: link
    force: true
