---

- name: Check for and load cached version
  include_tasks: "cached_version_fetch.yml"


# Case: File doesn't exist and no version has been set; find latest.
- name: Fetch and cache latest version when no override
  block:

    - name: Fetch the ServiceDesk metadata from marketplace
      set_fact:
        atl_servicedesk_version_json: "{{ lookup('url', '{{ atl_servicedesk_latest_url }}') }}"

    - name: Set the Jira version for ServiceDesk
      set_fact:
        atl_product_version: "{{ atl_servicedesk_version_json.name }}"

  when:
    not cached.stat.exists and
    (atl_product_version is undefined or
     not atl_product_version or
     atl_product_version == "latest")

- name: Cache download version if necessary
  include_tasks: "cached_version_write.yml"


- name: Set the download edition for ServiceDesk
  set_fact:
    atl_download_edition: "servicedesk"

- name: Fetch and unpack the product distribution
  include_tasks: "fetch_product.yml" 
