---

# Common case for most products and Jira editions.
- name: Fetch ServiceDesk metadata if necessary
  include_tasks: "servicedesk_download.yml"
  when: atl_product_edition == "jira-servicedesk"

# Differences for ServiceDesk become fiddly enough that it's better to
# just split them out and move common functionality into individual
# task files.
- name: Fetch product metadata if necessary
  include_tasks: "product_download.yml"
  when: atl_product_edition != "jira-servicedesk"
