---
- name: Converge
  hosts: all
  vars:
    atl_backup_manifest_url: 's3://dcd-slingshot-test/dummy_manifest.json'
    atl_product_user: 'jira'
    atl_backup_home_restore_canary_path: '/tmp/canary.tmp'

  roles:
    - restore_backups
