---
- hosts: aws_node_local
  become: true

  vars:
    atl_product_family: "jira"
    atl_product_edition: "jira-software"
    atl_product_user: "jira"

  roles:
    - linux_common
    - aws_common
    - aws_efs_config
    - product_common
    - product_download
    - database_config
    - jira_config
    - jira_startup
