---
- hosts: aws_node_local
  become: true

  vars:
    atl_product_family: "jira"
    atl_product_user: "jira"

    # FIXME: Slightly hacky workaround for specifying All or
    # ServiceDesk; override to use Software and install plugins later.
    atl_product_bundle: "{{ lookup('env', 'ATL_PRODUCT_EDITION') | lower }}"
    bundle_map:
      all: software
      servicedesk: software
      core: core
      software: software

    atl_product_edition: "jira-{{ bundle_map[atl_product_bundle] }}"

  roles:
    - linux_common
    - aws_common
    - aws_efs_config
    - product_common
    - product_download
    - database_config
    - jira_config
    - jira_startup
