---
- hosts: aws_node_local
  become: true

  vars:
    atl_product_family: "jira"
    atl_product_user: "jira"
    atl_product_edition: "jira-{{ lookup('env', 'ATL_PRODUCT_EDITION') | lower }}"

  roles:
    - role: linux_common
    - role: aws_common
    - role: aws_efs_config
    - role: product_common
    - role: installer_download
    - role: database_config
    - role: jira_config
    - role: jira_startup
