---
# This file was generated; to regnerated `cd` to `pipeline_generator`
# and run:
#
#    make > ../bitbucket-pipelines.yml

image: debian:buster
options:
  size: 2x

definitions:
  services:
    docker:
      memory: 4096

pipelines:
  default:
    - step:
        name: Pre Parallelization stage
        script:
          - echo "Running tests in 38 batches"
    - step:
        name: Check if number of batches match actual number of scenarios
        script:
          - |
              actual_scenario_count=$(find ./roles -type f -name "molecule.yml" -exec dirname {} ';' | wc -l |  sed -e 's/^[[:space:]]*//')
              grep  "Running tests in ${actual_scenario_count} batches" bitbucket-pipelines.yml
              GREP_RETURN_CODE=$?
              if [[ $GREP_RETURN_CODE -ne 0 ]]; then
                  echo "Mismatch between expected and actual number [${actual_scenario_count}] of scenarios. Please look at https://bitbucket.org/atlassian/dc-deployments-automation/src/master/DEVELOPMENT.md for instructions on how to fix this error."
                  exit $GREP_RETURN_CODE
              fi
    - parallel:
       - step:
           name: Molecule Test Batch - aws_common/cw-disabled
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 1
           
       - step:
           name: Molecule Test Batch - aws_common/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 2
           
       - step:
           name: Molecule Test Batch - aws_common/logs-disabled
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 3
           
       - step:
           name: Molecule Test Batch - bitbucket_config/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 4
           
       - step:
           name: Molecule Test Batch - confluence_config/aurora
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 5
           
       - step:
           name: Molecule Test Batch - confluence_config/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 6
           
       - step:
           name: Molecule Test Batch - confluence_config/password_char_escaping
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 7
           
       - step:
           name: Molecule Test Batch - confluence_config/system_jdk
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 8
           
       - step:
           name: Molecule Test Batch - create_backups/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 9
           
       - step:
           name: Molecule Test Batch - diy_backup/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 10
           
       - step:
           name: Molecule Test Batch - jira_config/aurora
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 11
           
       - step:
           name: Molecule Test Batch - jira_config/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 12
           
       - step:
           name: Molecule Test Batch - jira_config/jira_config_props
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 13
           
       - step:
           name: Molecule Test Batch - jira_config/password_char_escaping
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 14
           
       - step:
           name: Molecule Test Batch - linux_common/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 15
           
       - step:
           name: Molecule Test Batch - product_common/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 16
           
       - step:
           name: Molecule Test Batch - product_common/system_jdk
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 17
           
       - step:
           name: Molecule Test Batch - product_install/bitbucket_latest
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 18
           
       - step:
           name: Molecule Test Batch - product_install/confluence_latest
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 19
           
       - step:
           name: Molecule Test Batch - product_install/crowd_latest
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 20
           
       - step:
           name: Molecule Test Batch - product_install/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 21
           
       - step:
           name: Molecule Test Batch - product_install/jira_all
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 22
           
       - step:
           name: Molecule Test Batch - product_install/jira_cached_with_downgrade
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 23
           
       - step:
           name: Molecule Test Batch - product_install/jira_cached_with_upgrade
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 24
           
       - step:
           name: Molecule Test Batch - product_install/jira_software_latest
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 25
           
       - step:
           name: Molecule Test Batch - product_install/jira_tarball
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 26
           
       - step:
           name: Molecule Test Batch - product_install/jira_version_from_file
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 27
           
       - step:
           name: Molecule Test Batch - product_install/jira_version_latest
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 28
           
       - step:
           name: Molecule Test Batch - product_install/jira_version_override
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 29
           
       - step:
           name: Molecule Test Batch - product_install/servicedesk3
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 30
           
       - step:
           name: Molecule Test Batch - product_install/servicedesk4
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 31
           
       - step:
           name: Molecule Test Batch - product_install/servicedesk_latest
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 32
           
       - step:
           name: Molecule Test Batch - product_startup/bitbucket
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 33
           
       - step:
           name: Molecule Test Batch - product_startup/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 34
           
       - step:
           name: Molecule Test Batch - product_startup/synchrony
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 35
           
       - step:
           name: Molecule Test Batch - restore_backups/default
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 36
           
       - step:
           name: Molecule Test Batch - restore_backups/restore_conf_server
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 37
           
       - step:
           name: Molecule Test Batch - restore_backups/restore_jira_clustered
           services:
             - docker
           script:
           - apt-get update && ./bin/install-ansible --dev
           - ./bin/run-tests-in-batches --batch 38
           
       
