---

image: atlassian/default-image:2

definitions:
  services:
    docker:
      memory: 3072

pipelines:
  default:
    - step:
        services:
          - docker
        script:
          - apt-get update && apt-get install -y virtualenv python-dev
          - ./bin/install-ansible
          - ./bin/run-all-tests
