---
collections:
  - name: amazon.aws
    version: "6.1.0"
  - name: ansible.posix
    version: "1.5.4"
  - name: community.docker
    version: "3.4.8"
  - name: community.general
    version: "7.1.0"
  - name: community.postgresql
    version: "3.0.0"
