---
collections:
  - name: amazon.aws
    version: "5.5.0"
  - name: ansible.posix
    version: "1.5.4"
  - name: community.docker
    version: "3.4.5"
  - name: community.general
    version: "6.6.0"
  - name: community.postgresql
    version: "2.4.1"
