---

- block:

    - name: Parse the manifest URL
      set_fact:
        atl_backup_manifest_scheme: "{{ atl_backup_manifest_url | urlsplit('scheme') }}"
        atl_backup_manifest_bucket: "{{ atl_backup_manifest_url | urlsplit('hostname') }}"
        atl_backup_manifest_path: "{{ atl_backup_manifest_url | urlsplit('path') }}"
        atl_backup_manifest_filename: "{{ atl_backup_manifest_path | basename}}"
        atl_backup_manifest_dest: "{{ atl_installer_temp }}/{{ atl_backup_manifest_filename }}"

    - name: Fetch the manifest from S3
      aws_s3:
        bucket: "{{ atl_backup_manifest | urlsplit('hostname' }}"
        object: "{{ atl_backup_manifest | urlsplit('path' }}"
        dest: "{{ atl_installer_temp }}/{{ atl_backup_manifest | urlsplit('path' | }}"
      when: atl_backup_manifest_scheme == 's3'

    - name: Fetch the manifest from remote host
      get_url:
        url: "{{ atl_backup_manifest_url }}"
        dest: "{{ atl_backup_manifest_dest }}"
      when: atl_backup_manifest_scheme != 's3'

  when: atl_backup_manifest_url is defined and atl_backup_manifest_url != ''
