---

- name: Install JDK if necessary on Amazon Linux
  yum:
    name:
      - java-{{ java_version }}-openjdk-devel
  when: use_system_jdk

- name: Install other base packages on Amazon Linux
  yum:
    name:
      - dejavu-fonts-common  # Required by the installer

# Amazon Linux 2 supplies extra packages via a special command.
- name: Enable Postgresql from 'extras'
  command: amazon-linux-extras install -y "postgresql{{ postgres_version }}"
  args:
    creates: /usr/bin/psql
