---

- name: Retrieve all available EC2 tags
  ec2_tag:
    region: "{{ ansible_ec2_placement_region }}"
    resource: "{{ ansible_ec2_instance_id }}"
    state: list
  register: ec2_instance_tags

- name: Retrieve autoscaling group
  set_fact:
    ec2_autoscaling_group: "{{ ec2_tags.tags['aws:autoscaling:groupName'] | default('') }}"

- block:
    # No existing timestamp, so this is a first run. Persist some metadata into the ASG.
    - name: Fetch the git revision for this repo
      command:
        cmd: git rev-parse HEAD
      register: git_out

    - name: Setup the new ASG tags
      set_fact:
        deployment_firstrun_meta:
          - ResourceType: "auto-scaling-group"
            ResourceId: "{{ ec2_autoscaling_group }}"
            PropagateAtLaunch: true
            Key: "atl:deployment:commit"
            Value: "{{ git_out.stdout }}"

          - ResourceType: "auto-scaling-group"
            ResourceId: "{{ ec2_autoscaling_group }}"
            PropagateAtLaunch: true
            Key: "atl:deployment:first-run"
            Value: "{{ ansible_date_time.iso8601 }}"

    - name: Set the first-run tags on the ASG
      command: "aws autoscaling
                    create-or-update-tags
                    --region {{ ansible_ec2_placement_region }}
                    --tags '{{ deployment_firstrun_meta | to_json }}'"

  when:
    - ec2_autoscaling_group != ''
    - ec2_instance_tags.tags['atl:deployment:first-run'] is not defined
  ignore_errors: true
