---
- name: Converge
  hosts: all
  vars:
    atl_product_family: "confluence"
    atl_product_edition: "confluence"
    atl_product_user: "confluence"
    atl_product_version: "latest"
    atl_jdbc_user: 'confluence'
    atl_jvm_heap: 'PLACEHOLDER'
    atl_cluster_node_id: 'FAKEID'
    atl_autologin_cookie_age: "COOKIEAGE"
    ansible_ec2_local_ipv4: "1.1.1.1"
    ansible_default_ipv4: "2.2.2.2"

  roles:
    - role: linux_common
    - role: product_common
    - role: product_install
    - role: confluence_config
