---
- name: Converge
  hosts: all
  vars:
    atl_product_bundle: servicedesk
    bundle_map:
      all: software
      servicedesk: software
      core: core
      software: software

    atl_product_edition: "jira-{{ bundle_map[atl_product_bundle] }}"
    atl_product_family: "jira"
    atl_product_user: "jira"

  roles:
    - role: linux_common
    - role: product_common
    - role: product_download
