---

- name: Create Bitbucket config file
  template:
    src: bitbucket.properties.j2
    dest: "{{ atl_product_home_shared }}/bitbucket.properties"

- name: Remove write permissions from installation directory
  file:
    path: "{{ atl_product_installation_versioned }}"
    owner: "root"
    group: "root"
    mode: "u=rwX,g=rX,o=rX"
    recurse: true
