---

- name: Make sure mariadb is present
  become: true
  yum:
    name: mariadb
    state: present

- name: Make sure pymysql is present
  become: true
  pip:
    name: pymysql
    state: present

- name: Create application DB user
  mysql_user:
    login_host: "{{ atl_db_host }}"
    login_user: "{{ atl_db_root_user }}"
    login_password: "{{ atl_db_root_password }}"
    login_port: "{{ atl_db_port }}"
    name: "{{ atl_jdbc_user }}"
    password: "{{ atl_jdbc_password }}"

- block:

# RDS does not allow changing the collation on an existing DB, it only allows collation change on creation of db. If the db already exists, we need the “create new application database” task to be skipped, idempotence can not be relied upon as we cant be certain the collation of the existing db
    - name: Create new application database
      mysql_db:
        login_host: "{{ atl_db_host }}"
        login_user: "{{ atl_db_root_user }}"
        login_password: "{{ atl_db_root_password }}"
        login_port: "{{ atl_db_port }}"
        name: "{{ atl_jdbc_db_name }}"
        encoding: "{{ atl_jdbc_encoding }}"
        collation: "{{ atl_jdbc_collation }}"
      register: db_created 

  tags:
    - new_only

# - name: Assert ownership of public schema
#   postgresql_query:
#     login_host: "{{ atl_db_host }}"
#     login_user: "{{ atl_db_root_user }}"
#     login_password: "{{ atl_db_root_password }}"
#     db: "{{ atl_jdbc_db_name }}"
#     query: "ALTER SCHEMA public OWNER to {{ atl_db_root_user }};"

# - name: Grant privs to root user on public schema
#   postgresql_query:
#     login_host: "{{ atl_db_host }}"
#     login_user: "{{ atl_db_root_user }}"
#     login_password: "{{ atl_db_root_password }}"
#     db: "{{ atl_jdbc_db_name }}"
#     query: "GRANT ALL ON SCHEMA public TO {{ atl_db_root_user }};"

# - name: Grant privs to application user on public schema
#   postgresql_query:
#     login_host: "{{ atl_db_host }}"
#     login_user: "{{ atl_db_root_user }}"
#     login_password: "{{ atl_db_root_password }}"
#     db: "{{ atl_jdbc_db_name }}"
#     query: "GRANT ALL ON SCHEMA public TO {{ atl_jdbc_user }};"
