---
- name: Converge
  hosts: all
  vars:
    atl_product_user: "bitbucket"
    atl_product_family: "stash"
    atl_product_edition: "bitbucket"

  pre_tasks:
    - name: Create base dir
      file:
        path: '/opt/atlassian/'
        state: directory

    - name: Install git
      package:
        name: git
    
  roles:
    - role: diy_backup
