---

- name: Create Bitbucket dirs if necessary
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ atl_product_user_uid }}"
    group: "{{ atl_product_user_uid }}"
    mode: 0750
    state: directory
  with_items:
    - "{{ atl_home_base }}/{{ atl_product_edition }}"
    - "{{ mesh_install_dir }}"

- name: Template out the mesh service file
  ansible.builtin.template:
    src: mesh.service.j2
    dest: "/usr/lib/systemd/system/mesh.service"
    owner: "root"
    group: "root"
    mode: 0740

- name: download the mesh distribution using maven
  community.general.maven_artifact:
    group_id: "com.atlassian.bitbucket.mesh"
    artifact_id: "mesh-distribution"
    extension: "tar.gz"
    version: "{{ atl_product_version }}"
    repository_url: "{{ bitbucket_mesh_maven_repo }}"
    dest: "{{ mesh_install_dir }}"
    mode: "0644"
    owner: "{{ atl_product_user_uid }}"
    group: "{{ atl_product_user_uid }}"
  register: maven_download

- name: debug
  debug:
    var: maven_download