---

#
# STRUCTURE
#
# mode:
#   filesystem:
#     retained: []
#   database:
#     retained:
#       tables: []
#       queries:
#         table1:
#           - query1
#           - query2
#         table2:
#           - query3
#           - query4
#     substitutions:
#       tables:
#         - table1
#         - table2
#       strings:
#         string1: subst1
#         string2: subst2

#
# What we want for a CLONE PROVISION
#
clone:
  filesystem:
    retained:
      - '*/confluence.cfg.xml'
      - '*/synchrony-args.properties'
  database:
    retained:
      tables: []
      queries: {}
    substitutions:
      tables: []
      strings: []
    
#        
# What we (probably) want for a CLONE REFRESH
#
refresh:
  filesystem:
    retained:
      - '*/confluence.cfg.xml'
      - '*/synchrony-args.properties'
      - '*/keys/*'
      - '*/secrets-config.yaml'
      - '*/secured/*'
  database:
    retained:
      tables:
        - 'cwd_%'
        - AO_ED669C_IDP_CONFIG
        - BANDANA
      queries: {}
    substitutions:
      tables: []
      strings: []


