---

# https://github.com/fentik/JMXQuery.git
# This is a fork of the original that fixes json parsing
- name: Install jmxquery python module
  ansible.builtin.pip:
    name: git+https://github.com/fentik/JMXQuery.git#subdirectory=python
    extra_args: "--break-system-packages"

# Config file is app specific, so in app config role
- name: Install JMX monitoring script
  ansible.builtin.file:
    src: jmx_monitor.py
    dest: /usr/local/bin/jmx_monitor.py
    owner: root
    group: root
    mode: '0555'

