---

- name: Add atlassian-slingshot yum repository
  yum_repository:
    name: AtlassianSlingshot
    file: atlassian-slingshot
    state: present
    description: Atlassian Slingshot
    baseurl: "{{ atl_slingshot_yum_repo_url }}"
    gpgcheck: no

- name: Install atlassian-slingshot
  yum:
    name: atlassian-slingshot