---
- name: Install gnupg
  apt:
    name: gnupg
    state: present

- name: Add atlassian-slingshot debian repo public key
  apt_key:
    url: https://packages.atlassian.com/api/gpg/key/public
    state: present

- name: Add atlassian-slingshot debian repository
  apt_repository:
    repo: deb https://packages.atlassian.com/atlassian-slingshot-deb stable main
    state: present
    filename: atlassian-slingshot

- name: Install atlassian-slingshot
  apt:
    name: atlassian-slingshot
    update_cache: yes
    state: present