---

# # https://github.com/fentik/JMXQuery.git
# # This is a fork of the original that fixes json parsing
# - name: Install jmxquery python module
#   ansible.builtin.pip:
#     name: git+https://github.com/fentik/JMXQuery.git#subdirectory=python
#     extra_args: "--break-system-packages"

# # Config file is app specific, so in app config role
# - name: Install JMX monitoring script
#   ansible.builtin.copy:
#     src: jmx_monitor.py
#     dest: /usr/local/bin/jmx_monitor.py
#     owner: root
#     group: root
#     mode: '0555'

- name: Create checkmk service folder
  checkmk.general.folder:
    _terms: "~{{ checkmk_agent_folder }}"
    server_url: "{{ checkmk_agent_server_protocol }}://{{ checkmk_agent_server }}"
    site: "{{ checkmk_agent_site }}"
    api_user: "{{ checkmk_agent_user }}"
    api_secret: "{{ checkmk_agent_secret }}"
    validate_certs: false
    
  
- name: Import checkmk agent role
  ansible.builtin.import_role:
    name: checkmk.general.agent


- name: Download jolokia agent jar
  ansible.builtin.get_url:
    url: "{{ jolokia_agent_download_url }}"
    dest: "{{ jolokia_agent_jar }}"
    mode: '0440'
    owner: "{{ atl_product_user }}"
    group: "{{ atl_product_user }}"

- name: Install jolokia.cfg
  ansible.builtin.template:
    src: jolokia.cfg.j2
    dest: /etc/check_mk/jolokia.cfg

- name: Java jolokia startup
  ansible.builtin.copy:
    content: "-javaagent:{{ jolokia_agent_jar }}=port={{ jolokia_port }},host=localhost"
    dest: "{{ atl_product_installation_versioned }}/bin/jvm_custom_opts.d/jolokia"

- name: Install checkmk jolokia plugin
  ansible.builtin.get_url:
    url: "{{ jolokia_checkmk_plugin_url }}"
    dest: /usr/lib/check_mk_agent/plugins/mk_jolokia.py
    mode: "0755"
